[project]
name = "pydantic-collect-model-fields-reproducer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic==2.12",
    "pytest>=9.0.2",
    "pytest-profiling>=1.8.1",
    "snakeviz>=2.2.2",
]
